# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(599, 495)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.deleteFilmButton = QtWidgets.QPushButton(self.centralwidget)
        self.deleteFilmButton.setGeometry(QtCore.QRect(240, 10, 91, 23))
        self.deleteFilmButton.setObjectName("deleteFilmButton")
        self.editFilmButton = QtWidgets.QPushButton(self.centralwidget)
        self.editFilmButton.setGeometry(QtCore.QRect(120, 10, 91, 23))
        self.editFilmButton.setObjectName("editFilmButton")
        self.addFilmButton = QtWidgets.QPushButton(self.centralwidget)
        self.addFilmButton.setGeometry(QtCore.QRect(10, 10, 91, 23))
        self.addFilmButton.setObjectName("addFilmButton")
        self.filmsTable = QtWidgets.QTableWidget(self.centralwidget)
        self.filmsTable.setGeometry(QtCore.QRect(10, 50, 581, 421))
        self.filmsTable.setObjectName("filmsTable")
        self.filmsTable.setColumnCount(0)
        self.filmsTable.setRowCount(0)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Кофе"))
        self.deleteFilmButton.setText(_translate("MainWindow", "Удалить  кофе"))
        self.editFilmButton.setText(_translate("MainWindow", "Изменить  кофе"))
        self.addFilmButton.setText(_translate("MainWindow", "Добавить кофе"))
